[package]
name = "tegdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lru = "0.12.3"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
sled = "0.34.7" # for performance comparison
redb = "1.5.0"
rusqlite = "0.31.0"
tempfile = "3.10.1"

[[bench]]
name = "engine_basic_benchmark"
harness = false

[[bench]]
name = "engine_seq_benchmark"
harness = false
