[package]
name = "tegsql"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.1"
rayon = "1.8.0"
flate2 = "1.0.28"