[package]
name = "tegdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = "0.3"
sled = "0.34.7" # for performance comparison

[[bench]]
name = "engine_benchmark"
harness = false
