name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy, cargo
        profile: minimal
    - name: Build
      run: cargo build --lib
    - name: Run tests
      run: cargo test --lib
    - name: Run example
      run: cargo run --example basic_usage
    - name: Run benchmarks
      if: github.event_name == 'schedule'
      run: cargo bench > benchmarks.txt
    - name: Upload benchmark results
      if: github.event_name == 'schedule'
      uses: actions/upload-artifact@v4.3.1
      with:
        name: benchmark-results
        path: benchmarks.txt
