name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy, cargo
        profile: minimal
    - name: Build
      run: cargo build --lib --verbose
    - name: Run tests
      run: cargo test --lib --verbose
    - name: Run benchmarks
      if: github.event_name == 'schedule'
      run: cargo bench --lib --verbose > benchmarks.txt
    - name: Upload benchmark results
      if: github.event_name == 'schedule'
      uses: actions/upload-artifact@v2
      with:
        name: benchmark-results
        path: benchmarks.txt